Project:
  type: object
  required:
    - id
    - name
    - description
    - creatorId
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    description:
      type: string
    creatorId:
      type: integer
      format: int64

ProjectDetails:
  type: object
  required:
    - id
    - name
    - description
    - creatorId
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    description:
      type: string
    creatorId:
      type: integer
      format: int64
    volumes:
      type: array
      items:
        $ref: "./Volume.yaml#/VolumeDetails"
    models:
      type: array
      items:
        $ref: "./Model.yaml#/ModelDetails"
    User:
       $ref: "./User.yaml"