services:
  web:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile2
    image: ${IMAGE_NAME:-cocryovis:latest}
    container_name: volweb-app
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NODE_ENV=production
      - DATABASE_PATH=file:/app/database/db.sqlite
      - SESSION_SECRET=${SESSION_SECRET:-notsecret}
    volumes:
      - type: bind
        source: ./Ilastik/ilastik
        target: /app/modules/ilastik
      - app_dbdata:/app/database
      - app_filedata:/app/data
      - app_logdata:/app/logs
      - app_sessiondata:/app/sessions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command:
      [
        "sh",
        "-c",
        "npx prisma migrate deploy && npx prisma generate && conda run --no-capture-output -n volweb npm start -- --port 8080 --host 0.0.0.0 --demoProject 13",
      ]

volumes:
  app_dbdata:
  app_filedata:
  app_logdata:
  app_sessiondata:
