services:
  init-permissions:
    image: alpine
    user: root
    volumes:
      - app_dbdata:/database
      - ${APP_FILEDATA_PATH:-./.docker-volumes/data}:/data
    command: 
      [
        "sh",
        "-c",
        "chown -R 10001:10001 /database && chown -R 10001:10001 /data"
      ]
    restart: "no"

  web:
    depends_on:
      init-permissions:
        condition: service_completed_successfully
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
      args:
        CUDA_ARCHITECTURES: ${CUDA_ARCHITECTURES:-native}
        DATABASE_URL: file:/app/server/database/db.sqlite
    image: ${IMAGE_NAME:-cocryovis:latest}
    container_name: cocryovis
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NODE_ENV=production
      - SESSIONS_PATH=/app/server/database/db.sessions
      - SESSION_SECRET=${SESSION_SECRET:-notsecret}
      - ALLOW_INSECURE_COOKIES=${ALLOW_INSECURE_COOKIES:-false}
      - CROSS_SITE_COOKIES=${CROSS_SITE_COOKIES:-false}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # - DEMO_PROJECT=${DEMO_PROJECT}
      # - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - app_dbdata:/app/server/database
      - ${APP_FILEDATA_PATH:-./docker-volumes/data}:/app/server/data
      - app_logdata:/app/server/logs
      - app_modulecache:/app/server/.module-cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - cocryovis-network
    command:
      [
        "sh",
        "-c",
        "cd server && conda run --no-capture-output -n volweb sh -lc 'npm run db:setup && npm run start -- --port 8080 --host 0.0.0.0 --demoProject 2'"
      ]

volumes:
  app_dbdata:
  app_logdata:
  app_modulecache:

networks:
  cocryovis-network:
    driver: bridge